### ISSUE TITLE
[Bug]: command test-storybook fails with yarn-berry

### ISSUE THREAD

**Issue by atarek12** [storybookjs/test-runner#492] opened 2024-07-08 21:22 UTC
### Describe the bug

I got this error while trying to run `yarn test-storybook`

```text
Test suite failed to run

    TypeError: Function.prototype.apply was called on undefined, which is a undefined and not a function

      at node_modules/@storybook/test-runner/dist/index.js:13506:48
          at Array.reduce (<anonymous>)
      at transformCsf (node_modules/@storybook/test-runner/dist/index.js:13500:41)
      at transformPlaywright (node_modules/@storybook/test-runner/dist/index.js:13627:18)
      at Object.process (node_modules/@storybook/test-runner/playwright/transform.js:6:21)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:545:31)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:674:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:726:19)
```

### To Reproduce

When running `yarn test-storybook`, I got the error on each story file.
I have tried to run it against all browsers (chromium, firefox, webkit), but all gives the same error

the error occurs locally and on github action too, here is my workflow file

```yml
name: Run Tests on PR

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.16.0'

      - name: Instal Dependencies
        run: yarn install --frozen-lockfile

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Build Storybook
        run: yarn build-storybook --quiet

      - name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:127.0.0.1:6006 && yarn test-storybook"

```

### System

```bash
Storybook Environment Info:

  System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
  Binaries:
    Node: 20.11.1 - C:\Users\AHMEDT~1\AppData\Local\Temp\xfs-acc53f4e\node.CMD
    Yarn: 4.3.0 - C:\Users\AHMEDT~1\AppData\Local\Temp\xfs-acc53f4e\yarn.CMD <----- active
    npm: 10.2.4 - ~\.nvm\versions\node\v20.11.1\bin\npm.CMD
  Browsers:
    Edge: Chromium (126.0.2592.87)
  npmPackages:
    @storybook/addon-a11y: ^8.1.11 => 8.1.11
    @storybook/addon-actions: ^8.1.11 => 8.1.11
    @storybook/addon-designs: ^8.0.2 => 8.0.2
    @storybook/addon-essentials: ^8.1.11 => 8.1.11
    @storybook/addon-interactions: ^8.1.11 => 8.1.11
    @storybook/addon-links: ^8.1.11 => 8.1.11
    @storybook/addon-onboarding: ^8.1.11 => 8.1.11
    @storybook/blocks: ^8.1.11 => 8.1.11
    @storybook/react: ^8.1.11 => 8.1.11
    @storybook/react-vite: ^8.1.11 => 8.1.11
    @storybook/test: ^8.1.11 => 8.1.11
    @storybook/test-runner: ^0.19.0 => 0.19.0
    chromatic: ^11.4.0 => 11.4.0
    eslint-plugin-storybook: ^0.8.0 => 0.8.0
    storybook: ^8.1.11 => 8.1.11
    storybook-addon-performance: ^0.17.3 => 0.17.3
```

**Comment by atarek12** [comment] 2024-07-09 12:04
Updates: this error occures when using `yarn-berry`, it works now after downgrading to `yarn-classic`

**Comment by Romakita** [comment] 2024-07-10 08:28
@atarek12 
Adding resolutions field on package.json works also:

```json
{
  "resolutions": {
    "@storybook/csf": "0.1.11"
  }
}
```

**Comment by atarek12** [comment] 2024-07-10 10:13
Also if it help, it works when downgrading the `test-runner` to `"@storybook/test-runner": "^0.18.0",`

**Comment by chmmpagne** [comment] 2024-07-11 19:34
We ran into this as well with Yarn 4.3.1 after upgrading to 0.19 and switching from Webpack to Vite if that means anything.
Downgrading to 0.18 is our workaround as well.

**Comment by abenhamdine** [comment] 2024-07-12 14:12
Same error here, but we are already using `yarn-classic` and downgrading to 0.18 didn't solve the issue.  
This issues occurs since we upgraded storybook from v7 to v8

**Comment by yannbf** [comment] 2024-07-16 16:07
Hey everyone! This should be fixed in 0.19.1. Please try it out and report back!

**Closed by yannbf** 2024-07-16 16:07 UTC
Labels: bug, needs triage

**Comment by abenhamdine** [comment] 2024-07-16 16:37
Yes I confirm it works fine now, thx !

**Comment by atarek12** [comment] 2024-07-17 08:28
It works now, thank you 🚀

**Comment by ebk46** [comment] 2024-08-07 23:02
@yannbf Sorry to be the bearer of bad news, but I'm having the same problem on 0.19.1 - had to downgrade to 0.18.2 for it to work. Running with storybook@8.2.8 and yarn@1.22.21

**Comment by yannbf** [comment] 2025-01-02 09:06
Hey @ebk46 the issue was happening with Yarn Berry (v2 and higher) users. Seems like you're using Yarn Classic (v1). Did you try upgrading your dependencies, clearing your lockfile etc? Are you still having this issue? If so, can you make a reproduction repo?
