### ISSUE TITLE
[Bug] Sync issue in failures from one test affecting another test

### ISSUE THREAD

**Issue by yannbf** [storybookjs/test-runner#62] opened 2022-02-23 14:09 UTC
### Describe the bug

This seems not to be an actual bug in the test-runner, but rather in Storybook. Here's an example of a diagram that shows the sequence of steps in the test-runner:

![image](https://user-images.githubusercontent.com/1671563/155335199-c26387ea-f0a9-47cb-a2a7-1f0d31b0b2e7.png)

### Steps to reproduce the behavior

1. Change the `Demo` story in `Button.stories.js` from:
```
export const Demo = (args) => (
  <button type="button" onClick={() => args.onSubmit('clicked')}>
    Click
  </button>
);
```

to:
```
export const Demo = (args) => (
  <button type="button" onClick={() => { throw new Error('boom') }}>
    Click
  </button>
);
```

2. Run yarn test-storybook

The `boom` error should not leak into the `FindBy` story, which actually does not even use the same component as `Demo`:
![image](https://user-images.githubusercontent.com/1671563/155335664-e6c9ae18-4a1d-43c7-8429-c03612bede58.png)

**Comment by sneko** [comment] 2023-01-18 09:26
@yannbf don't know if it helps but awaiting in the `preRender()` helped me for a "similar" issue. https://github.com/storybookjs/test-runner/issues/244

**Comment by bryanjtc** [comment] 2023-02-02 21:26
Removing the following code from the testPrefixer in `transformPlaywright.ts` fixes this issue. By removing it, the error doesn't leak to the `FindBy` story and it is still shown at the `Demo` story.
```js
page.on('pageerror', (err) => {
          page.evaluate(({ id, err }) => __throwError(id, err), { id: %%id%%, err: err.message });
        });
```
It is not an ideal solution. Maybe I can find the cause in the `jest-playwright` package

**Comment by bryanjtc** [comment] 2023-07-01 06:12
I recently updated the pr to change the proposed fix for this issue.

**Closed** 2023-11-24 15:11 UTC
Labels: bug, sev:S2
